### ISSUE TITLE
[Docs] 템플릿 설정

### ISSUE THREAD

**Issue by mewmaze** [AhnSeene/find-my-meme-frontend#1]
### 💼 작업 설명
 템플릿 설정
 
### ✅ To-do

- [x] commit message 템플릿
- [x] feature issue 템플릿
- [x] bug issue 템플릿
- [x] pull request 템플릿
